# Generated by Django 3.2 on 2025-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templat/', verbose_name='Изображение'),
        ),
    ]
