# Generated by Django 3.2 on 2025-06-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prompttemplate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='app_id',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True, verbose_name='ID приложения')),
                ('name', models.CharField(max_length=255, verbose_name='Имя приложения')),
                ('templates', models.ManyToManyField(to='api.PromptTemplate', verbose_name='Связанные шаблоны')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.AddField(
            model_name='statistics',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.application', verbose_name='Приложение'),
        ),
    ]
